name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Java
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5433:5433
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        
    env:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5433
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install PSQL client
      run: |
        sudo apt-get update
        sudo apt-get install --yes --no-install-recommends postgresql-client
    - name: Create database
      run: |
        sudo psql -h localhost -p 5433 -U postgres -c 'CREATE DATABASE dicerolling;'
        sudo psql -h localhost -p 5433 -U postgres -c 'CREATE USER dicerollinguser WITH ENCRYPTED PASSWORD '12345678';'
        sudo psql -h localhost -p 5433 -U postgres -c 'GRANT ALL PRIVILEGES ON DATABASE dicerolling TO dicerollinguser;'
    - name: Set up JDK 18
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Install dependencies
      run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - name: Run tests and collect coverage
      run: mvn -B test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
