name: codecov-CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python API
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 18
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Install dependencies
      run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - name: Run tests and collect coverage
      run: mvn -B test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
