name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Java
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 18
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Install dependencies
      run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - name: Install dependencies
      run: npm ci
    - name: Connect to PostgreSQL
      env:
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5433
    - name: Install PSQL client
      run: |
        apt-get update
        apt-get install --yes --no-install-recommends postgresql-client
    - name: Create database
      run: |
        psql -h postgres -U postgres -c 'CREATE DATABASE dicerolling;'
        psql -h postgres -U postgres -c 'CREATE USER dicerollinguser WITH ENCRYPTED PASSWORD '12345678';'
        psql -h postgres -U postgres -c 'GRANT ALL PRIVILEGES ON DATABASE dicerolling TO dicerollinguser;'
    - name: Run tests and collect coverage
      run: mvn -B test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
